### ISSUE TITLE
Check for given arguments for sendVerificationCode

### ISSUE THREAD

**Issue by BlackYoup** [vvanghelue/digits-server-client#5]
Hi,

Currently, when this method is called, it doesn't check for arguments validity. For example, if one omits the `header` field, an error will be raised (`can't read property accept-languages of undefined`) and the program will crash. Also, this doesn't make much sense if the `phoneNumber` field is omitted too.

I would be glad to open a PR for this but how do you want to handle this ? Return a rejected Promise with an error describing the troubles or directly throw into the method ?

**Comment by vvanghelue** [comment]
The promise way seems good, what do you think ? You are welcome to open a PR, thanks !

**Comment by BlackYoup** [comment]
I like the Promise too, I'll open a PR tonight :-)
