### ISSUE TITLE
UnhandledPromiseRejectionWarning

### ISSUE THREAD

**Issue by joekh** [vvanghelue/digits-server-client#7]
Hello, 

I am receiving the warning below although the sendVerificationCode function is working properly and I am receiving the registrationToken, any idea?

(node:54611) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): ValidationError

**Comment by vvanghelue** [comment]
We just added some fix (make headers optionary) ? Can you check if you still get the error ?

**Comment by joekh** [comment]
@vvanghelue It's working properly now without any error, thank you
